#!/usr/bin/env bash
# TODO: 
# Add priority level into list but have it be pretty
# add failure messages
# maybe more?
function modify_task {
	# Add priority level option once that is added everywhere else
	actiond=`printf "Name\nDate" | rofi -dmenu -i -mesg 'What would you like to modify?'`
	if [ $actiond = Name ]; then
		newname=`rofi -dmenu -l 0 -mesg 'Enter new name'`
		taskid=`echo $actionb | awk '{print $1}'`
		todoist modify $taskid --content "$(echo $newname)" && rofi -dmenu -l 0 -mesg 'Task successfully modified.'
	fi
	if [ $actiond = Date ]; then
		newdate=`rofi -dmenu -l 0 -mesg 'Enter new date'`
		taskid=`echo $actionb | awk '{print $1}'`
		todoist modify $taskid --date "$(echo $newdate)" && rofi -dmenu -l 0 -mesg 'Task successfully modified.'
	fi
}
function add_task {
	taskname=`rofi -dmenu -i -l 0 -mesg 'Enter name of new task'`
	taskdate=`rofi -dmenu -i -l 0 -mesg 'Enter time and/or date of new task'`
	todoist add -d "$(echo $taskdate)" "$(echo $taskname)" && rofi -dmenu -l 0 -mesg 'Task successfully added.'
	main_menu
}
function quick_add {
	quickterm=`rofi -dmenu -l 0 -mesg 'Enter Quick Add syntax for new task'`
	todoist q "$(echo $quickterm)" && rofi -dmenu -l 0 -mesg 'Task successfully quick added'
	main_menu
}
function complete_task {
	if [ "$actionc" = Exit ]; then
		main_menu # should this go to main menu or just one menu above?
	else
		echo $actionb | awk '{print $1}' | xargs todoist c && rofi -dmenu -l 0 -mesg "Task successfully completed"
		main_menu
	fi
}
function sub_menu {
	taskchoice=`todoist l | awk '{print $6}'`
	actionc=`printf "Complete task\nModify task\nExit" | rofi -dmenu -i -l 4 -mesg 'Pick an action:'` 
	if [ "$actionc" = 'Complete task' ]; then
		complete_task
	fi
	if [ "$actionc" = 'Modify task' ]; then
		modify_task
	fi
}
function list_tasks {
	todoist sync
	tasklist=`todoist l | awk '{$2=$5=""; print $0}'`
	actionb=`printf "$tasklist\nExit" | rofi -dmenu -i -mesg 'Pick a task:'`
	if [ "$actionb" = Exit ]; then
		exec ~/.local/bin/rofi-todoist
	else
		sub_menu
	fi
}
function help_menu {
	rofi -dmenu -l 0 -mesg 'Use List Tasks option to list tasks. Selecting a task from this menu will prompt with actions to do, such as complete the task or modify it. Use the Add task option to add a task using explicit syntax. Use the Quick Add option to add a task using the Todoist smart Quick Add feature, where it recognizes the time, name, and date of the task by reading a sentence you write. At any time press the escape key to exit, and press the exit option to go up a menu.'	
}
function main_menu {
	action=`printf "List tasks\nQuick Add task\nAdd task\nHelp\nExit" | rofi -dmenu -i -l 5 -mesg 'Pick an action:'`
	if [ "$action" = "List tasks" ]; then
		list_tasks
	fi
	if [ "$action" = "Add task" ]; then
		add_task
	fi
	if [ "$action" = "Quick Add task" ]; then
		quick_add
	fi
	if [ "$action" = "Help" ]; then
		help_menu
	fi
}
main_menu
